FROM nginx:alpine

# Menentukan direktori kerja di dalam container
WORKDIR /app

# Menyalin seluruh konten dari direktori saat ini ke dalam direktori /app di dalam container
COPY pas.html /app/

# Menetapkan variabel lingkungan
ENV NAME World

# Memulai server Nginx ketika container dijalankan
CMD ["nginx", "-g", "daemon off;"]
