FROM nginx:alpine

# Menyalin file pas.html dari direktori lokal ke dalam direktori /usr/share/nginx/html di dalam container
COPY pas.html /usr/share/nginx/html/

# Menetapkan port yang akan di-Expose oleh container
EXPOSE 80

# Menjalankan perintah untuk memulai server Nginx
CMD ["nginx", "-g", "daemon off;"]

